<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Menu\Base;

use Knp\Menu\FactoryInterface;
use Knp\Menu\ItemInterface;
use Zikula\MenuModule\ExtensionMenu\ExtensionMenuInterface;
use Paustian\MelodyMixerModule\Helper\ControllerHelper;
use Paustian\MelodyMixerModule\Helper\PermissionHelper;

/**
 * This is the extension menu service base class.
 */
abstract class AbstractExtensionMenu implements ExtensionMenuInterface
{
    /**
     * @var FactoryInterface
     */
    protected $factory;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    public function __construct(
        FactoryInterface $factory,
        ControllerHelper $controllerHelper,
        PermissionHelper $permissionHelper
    ) {
        $this->factory = $factory;
        $this->controllerHelper = $controllerHelper;
        $this->permissionHelper = $permissionHelper;
    }

    public function get(string $type = self::TYPE_ADMIN): ?ItemInterface
    {
        $contextArgs = ['api' => 'extensionMenu', 'action' => 'get'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);

        $permLevel = self::TYPE_ADMIN === $type ? ACCESS_ADMIN : ACCESS_READ;

        $menu = $this->factory->createItem('paustianmelodymixermodule' . ucfirst($type) . 'Menu');

        if (self::TYPE_ACCOUNT === $type) {
            return 0 === $menu->count() ? null : $menu;
        }

        $routeArea = self::TYPE_ADMIN === $type ? 'admin' : '';
        if (self::TYPE_ADMIN === $type) {
            if ($this->permissionHelper->hasPermission(ACCESS_READ)) {
                $menu->addChild('Frontend', [
                    'route' => 'paustianmelodymixermodule_gamescore_index',
                ])
                    ->setAttribute('icon', 'fas fa-home')
                    ->setLinkAttribute('title', 'Switch to user area.')
                ;
            }
        } else {
            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $menu->addChild('Backend', [
                    'route' => 'paustianmelodymixermodule_gamescore_adminindex',
                ])
                    ->setAttribute('icon', 'fas fa-wrench')
                    ->setLinkAttribute('title', 'Switch to administration area.')
                ;
            }
        }
        
        if (
            in_array('gameScore', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('gameScore', $permLevel)
        ) {
            $menu->addChild('Game scores', [
                'route' => 'paustianmelodymixermodule_gamescore_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Game scores list')
                ->setExtra('translation_domain', 'gameScore')
            ;
        }
        if (
            in_array('score', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('score', $permLevel)
        ) {
            $menu->addChild('Scores', [
                'route' => 'paustianmelodymixermodule_score_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Scores list')
                ->setExtra('translation_domain', 'score')
            ;
        }
        if (
            in_array('level', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('level', $permLevel)
        ) {
            $menu->addChild('Levels', [
                'route' => 'paustianmelodymixermodule_level_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Levels list')
                ->setExtra('translation_domain', 'level')
            ;
        }
        if (
            in_array('graphicsAndSound', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('graphicsAndSound', $permLevel)
        ) {
            $menu->addChild('Graphics and sound', [
                'route' => 'paustianmelodymixermodule_graphicsandsound_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Graphics and sound list')
                ->setExtra('translation_domain', 'graphicsAndSound')
            ;
        }
        if (
            in_array('musicScore', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('musicScore', $permLevel)
        ) {
            $menu->addChild('Music scores', [
                'route' => 'paustianmelodymixermodule_musicscore_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Music scores list')
                ->setExtra('translation_domain', 'musicScore')
            ;
        }
        if ('admin' === $routeArea && $this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
            $menu->addChild('Settings', [
                'route' => 'paustianmelodymixermodule_config_config',
            ])
                ->setAttribute('icon', 'fas fa-wrench')
                ->setLinkAttribute('title', 'Manage settings for this application')
                ->setExtra('translation_domain', 'config')
            ;
        }

        return 0 === $menu->count() ? null : $menu;
    }

    public function getBundleName(): string
    {
        return 'PaustianMelodyMixerModule';
    }
}
