<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Form\Type\QuickNavigation;

use Paustian\MelodyMixerModule\Form\Type\QuickNavigation\Base\AbstractLevelQuickNavType;

/**
 * Level quick navigation form type implementation class.
 */
class LevelQuickNavType extends AbstractLevelQuickNavType
{
    // feel free to extend the base form type class here
}
