<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Form\Type;

use Paustian\MelodyMixerModule\Form\Type\Base\AbstractGraphicsAndSoundType;

/**
 * Graphics and sound editing form type implementation class.
 */
class GraphicsAndSoundType extends AbstractGraphicsAndSoundType
{
    // feel free to extend the graphics and sound editing form type class here
}
