<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Block;

use Paustian\MelodyMixerModule\Block\Base\AbstractItemListBlock;

/**
 * Generic item list block implementation class.
 */
class ItemListBlock extends AbstractItemListBlock
{
    // feel free to extend the item list block here
}
