<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Bundle\CoreBundle\Doctrine\EntityAccess;
use Paustian\MelodyMixerModule\Traits\StandardFieldsTrait;
use Paustian\MelodyMixerModule\Validator\Constraints as MelodyMixerAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for music score entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractMusicScoreEntity extends EntityAccess
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'musicScore';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var int $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     *
     * @ORM\Column(length=20)
     * @Assert\NotBlank
     * @MelodyMixerAssert\ListEntry(entityName="musicScore", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     * @Assert\NotBlank
     * @Assert\NotEqualTo(value=0)
     * @Assert\LessThan(value=100000000000)
     * @var int $levelId
     */
    protected $levelId = 0;
    
    /**
     * The example number for this level
     *
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     * @Assert\NotBlank
     * @Assert\NotEqualTo(value=0)
     * @Assert\LessThan(value=100000000000)
     * @var int $exNum
     */
    protected $exNum = 0;
    
    /**
     * The name of the graphic to load and score
     *
     * @ORM\Column(length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="0", max="255", allowEmptyString="false")
     * @var string $gsGraphic
     */
    protected $gsGraphic = '';
    
    /**
     * The name of the midi file to play
     *
     * @ORM\Column(length=255)
     * @Assert\NotBlank
     * @Assert\Length(min="0", max="255", allowEmptyString="false")
     * @var string $gsMidi
     */
    protected $gsMidi = '';
    
    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     * @Assert\NotNull
     * @Assert\LessThan(value=100000000000)
     * @var int $scoreIt
     */
    protected $scoreIt = 0;
    
    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     * @Assert\NotNull
     * @Assert\LessThanOrEqual(value=4)
     * @var int $musicOrder
     */
    protected $musicOrder = 0;
    
    
    
    /**
     * MusicScoreEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
    }
    
    public function get_objectType(): string
    {
        return $this->_objectType;
    }
    
    public function set_objectType(string $_objectType): void
    {
        if ($this->_objectType !== $_objectType) {
            $this->_objectType = $_objectType ?? '';
        }
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function setId(int $id = null): void
    {
        if ((int)$this->id !== $id) {
            $this->id = $id;
        }
    }
    
    public function getWorkflowState(): string
    {
        return $this->workflowState;
    }
    
    public function setWorkflowState(string $workflowState): void
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = $workflowState ?? '';
        }
    }
    
    public function getLevelId(): int
    {
        return $this->levelId;
    }
    
    public function setLevelId(int $levelId): void
    {
        if ((int)$this->levelId !== $levelId) {
            $this->levelId = $levelId;
        }
    }
    
    public function getExNum(): int
    {
        return $this->exNum;
    }
    
    public function setExNum(int $exNum): void
    {
        if ((int)$this->exNum !== $exNum) {
            $this->exNum = $exNum;
        }
    }
    
    public function getGsGraphic(): string
    {
        return $this->gsGraphic;
    }
    
    public function setGsGraphic(string $gsGraphic): void
    {
        if ($this->gsGraphic !== $gsGraphic) {
            $this->gsGraphic = $gsGraphic ?? '';
        }
    }
    
    public function getGsMidi(): string
    {
        return $this->gsMidi;
    }
    
    public function setGsMidi(string $gsMidi): void
    {
        if ($this->gsMidi !== $gsMidi) {
            $this->gsMidi = $gsMidi ?? '';
        }
    }
    
    public function getScoreIt(): int
    {
        return $this->scoreIt;
    }
    
    public function setScoreIt(int $scoreIt): void
    {
        if ((int)$this->scoreIt !== $scoreIt) {
            $this->scoreIt = $scoreIt;
        }
    }
    
    public function getMusicOrder(): int
    {
        return $this->musicOrder;
    }
    
    public function setMusicOrder(int $musicOrder): void
    {
        if ((int)$this->musicOrder !== $musicOrder) {
            $this->musicOrder = $musicOrder;
        }
    }
    
    /**
     * Creates url arguments array for easy creation of display urls.
     */
    public function createUrlArgs(): array
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     */
    public function getKey(): ?int
    {
        return $this->getId();
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     */
    public function getRelatedObjectsToPersist(array &$objects = []): array
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     */
    public function __toString(): string
    {
        return 'Music score ' . $this->getKey() . ': ' . $this->getGsGraphic();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    }
}
