<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Event\Base;

use Paustian\MelodyMixerModule\Entity\ScoreEntity;

/**
 * Event base class for filtering score processing.
 */
class AbstractScorePreRemoveEvent
{
    /**
     * @var ScoreEntity Reference to treated entity instance.
     */
    protected $score;

    public function __construct(ScoreEntity $score)
    {
        $this->score = $score;
    }

    /**
     * @return ScoreEntity
     */
    public function getScore(): ScoreEntity
    {
        return $this->score;
    }
}
