<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Event\Base;

use Paustian\MelodyMixerModule\Entity\MusicScoreEntity;

/**
 * Event base class for filtering music score processing.
 */
class AbstractMusicScorePostPersistEvent
{
    /**
     * @var MusicScoreEntity Reference to treated entity instance.
     */
    protected $musicScore;

    public function __construct(MusicScoreEntity $musicScore)
    {
        $this->musicScore = $musicScore;
    }

    /**
     * @return MusicScoreEntity
     */
    public function getMusicScore(): MusicScoreEntity
    {
        return $this->musicScore;
    }
}
