<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Entity\Repository;

use Paustian\MelodyMixerModule\Entity\Repository\Base\AbstractMusicScoreRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for music score entities.
 */
class MusicScoreRepository extends AbstractMusicScoreRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
    public function selectMusicScoresFromLevel(int $level, int $exNum) : array {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(array('tbl'))
            ->from($this->mainEntityClass, 'tbl')
            ->where($qb->expr()->eq('tbl.levelId', '?1'))
            ->andWhere($qb->expr()->eq('tbl.exNum', '?2'))
            ->setParameters([1 => $level, 2 => $exNum]);
        return $this->getQueryFromBuilder($qb)->getArrayResult();
    }
}
