<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Entity\Repository;

use Paustian\MelodyMixerModule\Entity\Repository\Base\AbstractScoreRepository;
use Paustian\MelodyMixerModule\Entity\ScoreEntity;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for score entities.
 */
class ScoreRepository extends AbstractScoreRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
    public function findUserScore(int $level, int $uid){
        $qb = $this->_em->createQueryBuilder();
        $qb->select(array('tbl'))
            ->from($this->mainEntityClass, 'tbl')
            ->where($qb->expr()->eq('tbl.levelId', '?1'))
            ->andWhere($qb->expr()->eq('tbl.playerUid', '?2'))
            ->setParameters([1 => $level, 2 => $uid]);

        return $this->getQueryFromBuilder($qb)->getResult();
    }

    public function getScores($levelId, int $uid){
        $result = $this->findUserScore($levelId, (int)$uid);
        if(count($result) > 0){
            $scores = $result[0];
            $retScores = [];
            $retScores[0] = $scores->getScoreOne();
            $retScores[1] = $scores->getScoreTwo();
            $retScores[2] = $scores->getScoreThree();
            $retScores[3] = $scores->getScoreFour();
            $retScores[4] = $scores->getScoreFive();
            $retScores[5] = $scores->getScoreSix();
            $retScores[6] = $scores->getScoreSeven();
            $retScores[7] = $scores->getScoreEight();
            $retScores[8] = $scores->getScoreNine();
            $retScores[9] = $scores->getScoreTen();
        } else{
            $retScores = [0,0,0,0,0,0,0,0,0,0];
        }
        return $retScores;
    }
}
