<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Translation\Extractor\Annotation\Ignore;
use Translation\Extractor\Annotation\Translate;
use Paustian\MelodyMixerModule\Entity\Factory\EntityFactory;
use Paustian\MelodyMixerModule\Entity\GraphicsAndSoundEntity;
use Paustian\MelodyMixerModule\Helper\CollectionFilterHelper;
use Paustian\MelodyMixerModule\Helper\EntityDisplayHelper;
use Paustian\MelodyMixerModule\Helper\ListEntriesHelper;
use Paustian\MelodyMixerModule\Traits\ModerationFormFieldsTrait;

/**
 * Graphics and sound editing form type base class.
 */
abstract class AbstractGraphicsAndSoundType extends AbstractType
{
    use ModerationFormFieldsTrait;

    /**
     * @var EntityFactory
     */
    protected $entityFactory;

    /**
     * @var CollectionFilterHelper
     */
    protected $collectionFilterHelper;

    /**
     * @var EntityDisplayHelper
     */
    protected $entityDisplayHelper;

    /**
     * @var ListEntriesHelper
     */
    protected $listHelper;

    public function __construct(
        EntityFactory $entityFactory,
        CollectionFilterHelper $collectionFilterHelper,
        EntityDisplayHelper $entityDisplayHelper,
        ListEntriesHelper $listHelper
    ) {
        $this->entityFactory = $entityFactory;
        $this->collectionFilterHelper = $collectionFilterHelper;
        $this->entityDisplayHelper = $entityDisplayHelper;
        $this->listHelper = $listHelper;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addEntityFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addSubmitButtons($builder, $options);
    }

    /**
     * Adds basic entity fields.
     */
    public function addEntityFields(FormBuilderInterface $builder, array $options = []): void
    {
        
        $builder->add('levelid', IntegerType::class, [
            'label' => 'Levelid:',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the levelid of the graphics and sound. Only digits are allowed.'
            ],
            'required' => true,
        ]);
        
        $builder->add('gsName', TextType::class, [
            'label' => 'Gs name:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The name of the graphic'
            ],
            'help' => 'The name of the graphic',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => 'Enter the gs name of the graphics and sound.'
            ],
            'required' => true,
        ]);
        
        $builder->add('gsPath', TextType::class, [
            'label' => 'Gs path:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The path to the graphic/sound'
            ],
            'help' => 'The path to the graphic/sound',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => 'Enter the gs path of the graphics and sound.'
            ],
            'required' => true,
        ]);
        
        $builder->add('xPos', IntegerType::class, [
            'label' => 'X pos:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The x position of the graphic on the stage'
            ],
            'help' => 'The x position of the graphic on the stage',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the x pos of the graphics and sound. Only digits are allowed.'
            ],
            'required' => false,
        ]);
        
        $builder->add('yPos', IntegerType::class, [
            'label' => 'Y pos:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The y position of the graphic on the stage'
            ],
            'help' => 'The y position of the graphic on the stage',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the y pos of the graphics and sound. Only digits are allowed.'
            ],
            'required' => false,
        ]);
        
        $builder->add('descText', TextareaType::class, [
            'label' => 'Desc text:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'Any text the graphic might want to say'
            ],
            /** @Ignore */
            'help' => [
                /** @Translate */'Any text the graphic might want to say',
                /** @Translate */'Note: this value must not exceed %length% characters.',
            ],
            'help_translation_parameters' => ['%length%' => 2000],
            'empty_data' => '',
            'attr' => [
                'maxlength' => 2000,
                'class' => '',
                'title' => 'Enter the desc text of the graphics and sound.'
            ],
            'required' => false,
        ]);
        
        $builder->add('xDes', IntegerType::class, [
            'label' => 'X des:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The position of the descriptive text box'
            ],
            'help' => 'The position of the descriptive text box',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the x des of the graphics and sound. Only digits are allowed.'
            ],
            'required' => false,
        ]);
        
        $builder->add('yDes', IntegerType::class, [
            'label' => 'Y des:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The y position of the descriptive text'
            ],
            'help' => 'The y position of the descriptive text',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the y des of the graphics and sound. Only digits are allowed.'
            ],
            'required' => false,
        ]);
        
        $builder->add('boxWidth', IntegerType::class, [
            'label' => 'Box width:',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => 'The width of the descriptive text box'
            ],
            'help' => 'The width of the descriptive text box',
            'empty_data' => 0,
            'attr' => [
                'maxlength' => 11,
                'class' => '',
                'title' => 'Enter the box width of the graphics and sound. Only digits are allowed.'
            ],
            'required' => false,
        ]);
        
        $builder->add('graphicAtBottom', CheckboxType::class, [
            'label' => 'Graphic at bottom:',
            'label_attr' => [
                'class' => 'tooltips switch-custom',
                'title' => 'Shoud the graphic be placed at the bottom of the stage. '
            ],
            'help' => 'Shoud the graphic be placed at the bottom of the stage. ',
            'attr' => [
                'class' => '',
                'title' => 'graphic at bottom ?'
            ],
            'required' => false,
        ]);
    }

    /**
     * Adds submit buttons.
     */
    public function addSubmitButtons(FormBuilderInterface $builder, array $options = []): void
    {
        foreach ($options['actions'] as $action) {
            $builder->add($action['id'], SubmitType::class, [
                /** @Ignore */
                'label' => $action['title'],
                'icon' => 'delete' === $action['id'] ? 'fa-trash-alt' : '',
                'attr' => [
                    'class' => $action['buttonClass']
                ]
            ]);
            if ('create' === $options['mode'] && 'submit' === $action['id'] && !$options['inline_usage']) {
                // add additional button to submit item and return to create form
                $builder->add('submitrepeat', SubmitType::class, [
                    'label' => 'Submit and repeat',
                    'icon' => 'fa-repeat',
                    'attr' => [
                        'class' => $action['buttonClass']
                    ]
                ]);
            }
        }
        $builder->add('reset', ResetType::class, [
            'label' => 'Reset',
            'icon' => 'fa-sync',
            'attr' => [
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
        $builder->add('cancel', SubmitType::class, [
            'label' => 'Cancel',
            'validate' => false,
            'icon' => 'fa-times'
        ]);
    }

    public function getBlockPrefix()
    {
        return 'paustianmelodymixermodule_graphicsandsound';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => GraphicsAndSoundEntity::class,
                'translation_domain' => 'graphicsAndSound',
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createGraphicsAndSound();
                },
                'error_mapping' => [
                ],
                'mode' => 'create',
                'actions' => [],
                'has_moderate_permission' => false,
                'allow_moderation_specific_creator' => false,
                'allow_moderation_specific_creation_date' => false,
                'filter_by_ownership' => true,
                'inline_usage' => false
            ])
            ->setRequired(['mode', 'actions'])
            ->setAllowedTypes('mode', 'string')
            ->setAllowedTypes('actions', 'array')
            ->setAllowedTypes('has_moderate_permission', 'bool')
            ->setAllowedTypes('allow_moderation_specific_creator', 'bool')
            ->setAllowedTypes('allow_moderation_specific_creation_date', 'bool')
            ->setAllowedTypes('filter_by_ownership', 'bool')
            ->setAllowedTypes('inline_usage', 'bool')
            ->setAllowedValues('mode', ['create', 'edit'])
        ;
    }
}
