<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Menu;

use Paustian\MelodyMixerModule\Menu\Base\AbstractExtensionMenu;
use Knp\Menu\ItemInterface;

/**
 * This is the extension menu service implementation class.
 */
class ExtensionMenu extends AbstractExtensionMenu
{
    // feel free to add own extensions here
    public function get(string $type = self::TYPE_ADMIN): ? ItemInterface
    {
        $menu = parent::get($type);
        if(null === $menu){
            return $menu;
        }
        if($type == self::TYPE_ADMIN){
            $menu->addChild('Tools', [
                'uri' => '#',
            ])->setAttribute('icon', 'fas fa-tools')
                ->setAttribute('dropdown', true);

            $menu->getChild('Tools')->addChild('Import Data', [
                'route' => 'paustianmelodymixermodule_navi_import',
            ])->setAttribute('icon', 'fas fa-file-import');
            $menu->getChild('Tools')->addChild('Fill Level Info', [
                'route' => 'paustianmelodymixermodule_level_filllevel',
            ])->setAttribute('icon', 'fas fa-fill-drip');
        }
        return 0 === $menu->count() ? null : $menu;
    }
}
