<?php

/**
 * MelodyMixer.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytextbook.com
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\MelodyMixerModule\Entity\Factory\Base;

use Paustian\MelodyMixerModule\Entity\GameScoreEntity;
use Paustian\MelodyMixerModule\Entity\ScoreEntity;
use Paustian\MelodyMixerModule\Entity\LevelEntity;
use Paustian\MelodyMixerModule\Entity\GraphicsAndSoundEntity;
use Paustian\MelodyMixerModule\Entity\MusicScoreEntity;
use Paustian\MelodyMixerModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    public function __construct(
        PermissionHelper $permissionHelper
    ) {
        $this->permissionHelper = $permissionHelper;
    }

    /**
     * Initialises a given gameScore instance.
     */
    public function initGameScore(GameScoreEntity $entity): GameScoreEntity
    {
        return $entity;
    }

    /**
     * Initialises a given score instance.
     */
    public function initScore(ScoreEntity $entity): ScoreEntity
    {
        return $entity;
    }

    /**
     * Initialises a given level instance.
     */
    public function initLevel(LevelEntity $entity): LevelEntity
    {
        return $entity;
    }

    /**
     * Initialises a given graphicsAndSound instance.
     */
    public function initGraphicsAndSound(GraphicsAndSoundEntity $entity): GraphicsAndSoundEntity
    {
        return $entity;
    }

    /**
     * Initialises a given musicScore instance.
     */
    public function initMusicScore(MusicScoreEntity $entity): MusicScoreEntity
    {
        return $entity;
    }
}
